// Auto-generated by extract_icon_ids.py. Do not edit manually.
namespace TravStickers.TravStickersCode;

public static class GameAscensionIds
{
    public static readonly string[] All =
    {
        "top_bar_ascension",
        "score_ascension",
    };
}
