// Auto-generated by extract_icon_ids.py. Do not edit manually.
namespace TravStickers.TravStickersCode;

public static class GameBadgeIds
{
    public static readonly string[] All =
    {
        "badge_big_deck",
        "badge_bronze",
        "badge_ccccombo",
        "badge_curses",
        "badge_damage_leader",
        "badge_debuffer",
        "badge_double_snecko",
        "badge_elite",
        "badge_famished",
        "badge_favorite_card",
        "badge_glutton",
        "badge_gold",
        "badge_healer",
        "badge_highlander",
        "badge_honed",
        "badge_ilikeshiny",
        "badge_kaching",
        "badge_money_money",
        "badge_mystery_machine",
        "badge_outline",
        "badge_perfect",
        "badge_restful",
        "badge_restless",
        "badge_silver",
        "badge_speedy",
        "badge_tablet",
        "badge_team_player",
        "badge_tiny_deck",
        "badge_whomper",
    };
}
